### ISSUE TITLE
can't create a '_file_sessionid' files, message = "{"event":"client-call","data":null}"

### ISSUE THREAD

**Issue by xuzhousoft09** [nielsbaloe/webrtc-php#11]
Hello my brother,

I still couldn't create the file under my document root directory.
although I didn't get any error at F12.
I think my problem is in 

...
 xhttp.open("POST", URL, true);
 xhttp.setRequestHeader("Content-Type","Application/X-Www-Form-Urlencoded");
xhttp.send(message);  // here, the "message" always  was {"event":"client-call","data":null}.
...

If I change the :

> else if (count($_POST )!= 0) {...}

to:

> else if (count($_POST) == 0) {...}

It could create a '_file_sessionid' file with a value of {"event":"client-call","data":null}.

Should I switch to a centos 7 server? I am using win10 right now.

If you have any idea, please give me an advise.
Thank you in advance!

![image](https://user-images.githubusercontent.com/12077057/85747884-3e558680-b73a-11ea-95cf-cd2610bf4296.png)

**Comment by nielsbaloe** [comment]
Hmm, I think I can not follow what is wrong.
I do not think there is a script error.
I like your idea of switching to a unix server, because it was tested by me under a unix server. I guess that would at least get it running. Big chance that there is a file I/O thing  that does not occur on unix.......
You got my respect for staying with the problem!

Best,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: xuzhousoft09 <notifications@github.com>
Verzonden: donderdag 25 juni 2020 17:18
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] can't create a '_file_sessionid' files, message = "{"event":"client-call","data":null}" (#11)


Hello my brother,

I still couldn't create the file under my document root directory.
although I didn't get any error at F12.
I think my problem is in

...
xhttp.open("POST", URL, true);
xhttp.setRequestHeader("Content-Type","Application/X-Www-Form-Urlencoded");
xhttp.send(message); // here, the "message" always was {"event":"client-call","data":null}.
...

If I change the :

else if (count($_POST )!= 0) {...}

to:

else if (count($_POST) == 0) {...}

It could create a '_file_sessionid' file with a value of {"event":"client-call","data":null}.

Should I switch to a centos 7 server? I am using win10 right now.

If you have any idea, please give me a advise.
Thank you in advance!

[image]<https://user-images.githubusercontent.com/12077057/85747780-2847c600-b73a-11ea-93b9-e92118870c9e.png>

**Comment by xuzhousoft09** [comment]
It still couldn't create a file under my document root directory.

![捕获](https://user-images.githubusercontent.com/12077057/85912003-9afc9280-b85b-11ea-9ead-a37fd20fb846.PNG)

**Comment by xuzhousoft09** [comment]
Hello my dear frends.

Every time I run this project, it posts a {"event":"client-call","data":null} to the server side. Is it right?
I think instead of {"event":"client-call","**data":null**}  it shoud post some data to the server side, so that at the server side, it can pass the condition 

> else if (count($_POST)!=0)

then, executes 

> ...
>  $filename = '_file_' /* .$room */ .session_id();
>  $posted = file_get_contents('php://input');
> ...

Am I right?

![2](https://user-images.githubusercontent.com/12077057/85912379-a43b2e80-b85e-11ea-869c-ff9c6ca59510.png)
