### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by bodispatrik** [nielsbaloe/webrtc-php#18]
Hi, I want to ask for your help in that in my case the connection doesn't always happen. Is it any idea how to check the through data and if you don't have to refresh the page to reconnect? Thank you in advance for your help

**Comment by nielsbaloe** [comment]
Hi,

Well, it depends on which variables are in use and where the connection fails. Usually it works  to reset the variables that are involved (all of them!) and do again whatever happens when you load the page... a lot of work to put this in there, but you will succeed!


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: bodispatrik <notifications@github.com>
Verzonden: zaterdag 28 november 2020 15:16
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Reconnecting (#18)


Hi, I want to ask for your help in that in my case the connection doesn't always happen. Is it any idea how to check the through data and if you don't have to refresh the page to reconnect? Thank you in advance for your help
