### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by bodispatrik** [nielsbaloe/webrtc-php#19]
Do you think ssh is secure enough? shouldn't there be other encryption?

**Comment by nielsbaloe** [comment]
Hi,

SSL is enough so that people do not evesdrop on catching messages. And, a pitfall is that as a user you are handing out "unique" keys - what would be safer is that the server hands that out! Does that help?


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: bodispatrik <notifications@github.com>
Verzonden: zaterdag 28 november 2020 15:17
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Safety (#19)


Do you think ssh is secure enough? shouldn't there be other encryption?
