### ISSUE TITLE
Signaling part (initiate / answer part) to establish a webrtc session e2e?

### ISSUE THREAD

**Issue by pwFoo** [nielsbaloe/webrtc-php#3]
Hi @nielsbaloe,

thanks for sharing. I have to test it soon and read the code too...

At the moment I'm searching for a php (cheap hosting) solution for a webrtc chat / signaling (I think... I'm neew with that topic...).

I found https://github.com/feross/simple-peer which looks nice to handle webrtc, but needs signaling (initiate / answer exchange part). Looks like your code should do that for me?

But I'm not sure about the exchange part and code parts which relevant to establish the client to client webrtc session?

> It is just one file divided in three parts: 
> the client (browser), 
> the server for ajax posts which writes received data to a file,
> and the server for sending EventSource messages which are read from a file.

What is send to the server and written to file?

Could you help me with some code hints?

**Comment by nielsbaloe** [comment]
Well, my code does all the parts, not only the webrtc but also the signalling. I would say: just take a look at the code. It is really very easy. You can see the division yourself. If you have ever done something with HTML or PHP you see the division crystalclear and it will take you a few minuts to create two or three files out of it. Only when this division is really withholding you from getting any further, give me a ring and I will split it.

The first part is just HTML including some javascript.
The middle part is where the stuff comes in and is written _to_ disk.
The third part is where both clients request incoming messages, which are read _from_ disk (and deleted too).

I am afraid I do not have time to help you much further,

Best,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: pwFoo <notifications@github.com>
Verzonden: donderdag 1 augustus 2019 17:13
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Signaling part (initiate / answer part) to establish a webrtc session e2e? (#3)


Hi @nielsbaloe<https://github.com/nielsbaloe>,

thanks for sharing. I have to test it soon and read the code too...

At the moment I'm searching for a php (cheap hosting) solution for a webrtc chat / signaling (I think... I'm neew with that topic...).

I found https://github.com/feross/simple-peer which looks nice to handle webrtc, but needs signaling (initiate / answer exchange part). Looks like your code should do that for me?

But I'm not sure about the exchange part and code parts which relevant to establish the client to client webrtc session?

It is just one file divided in three parts:
the client (browser),
the server for ajax posts which writes received data to a file,
and the server for sending EventSource messages which are read from a file.

What is send to the server and written to file?

Could you help me with some code hints?

**Comment by pwFoo** [comment]
Thanks, looked into source code and tested it. Video works fine, but audio is one site only (desktop pc, I hear myself) and no audio in / out (with chrome for android at mobile). Have you tested it with mobile too?

The file is used for webrtc signaling (invite, offer, ...). Maybe I move that part to database (mysql, sqlite) instead of simple file.
Some kind of auth could be done by path (room) or some client data validation (don't exchange data if validation fails)?

Awesome to do it with a simple php hosting!

**Comment by nielsbaloe** [comment]
Hi,

Ah great that it works out.

The audio is disabled in the code. Look for it in the javascript. I had it turned off because I did not had a microphone at my (regular) raspbian-based machine to test it with. But it is just one line, if you enable it, it should work. I tested it with mobile too yes.

As long as your application stays small, yes you can of course use a database and add authorization. However if you have the slightest plan of expanding it, you might want to shift to websockets now and don't "waste' your energie on this part. I did it with a file because it is useless to spend much energy and time (like database/authorisation) in it if nobody is going to use it in a bigger scale anyway.

I'm really glad that it helps you forward in your creativity and usability of webrtc - I wrote it in the first place to make that possible!

Best,

Niels
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: pwFoo <notifications@github.com>
Verzonden: donderdag 1 augustus 2019 19:44
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Signaling part (initiate / answer part) to establish a webrtc session e2e? (#3)


Thanks, looked into source code and tested it. Video works fine, but audio is one site only (desktop pc, I hear myself) and no audio in / out (with chrome for android at mobile). Have you tested it with mobile too?

The file is used for webrtc signaling (invite, offer, ...). Maybe I move that part to database (mysql, sqlite) instead of simple file.
Some kind of auth could be done by path (room) or some client data validation (don't exchange data if validation fails)?

Awesome to do it with a simple php hosting!

**Comment by pwFoo** [comment]
audio was activated, but looks like audio was blocked on android device and I need to mute local video to eliminate the echo.
```
<video id="localVideo" autoplay=false muted></video>
```

Found it here:
https://stackoverflow.com/questions/18406193/how-to-avoid-echo-and-noise-in-javascript-for-webrtc
