### ISSUE TITLE
error "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

### ISSUE THREAD

**Issue by xuzhousoft09** [nielsbaloe/webrtc-php#9]
Hello, niels.

I set up your project and opened it on my Firefox 77.0.1.
I got an error "Firefox can not connect to https://localhost/webrtc-php/serverGet.php?unique=899215"

![image](https://user-images.githubusercontent.com/12077057/85197793-fee00200-b315-11ea-9244-21fb030da507.png)

and I also tried it on my chrome Version 83.0.4103.106, I got an error "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

![image](https://user-images.githubusercontent.com/12077057/85197953-2daaa800-b317-11ea-8264-b429672ec70f.png)

could you please tell me how to solve these errors?

**Comment by nielsbaloe** [comment]
Hi,

I will take a look at it later, I am pretty over-occupied at the moment.

For now, I think it does not work at all because you do not have a valid HTTPS certificate. The https is not for show, it really has to function fully. Just put it onto a server with https and I think you will get it working right away (or nearly right away).

Best,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: xuzhousoft09 <notifications@github.com>
Verzonden: zaterdag 20 juni 2020 10:57
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Firefox can not connect to https://localhost/webrtc-php/serverGet.php?unique=899215 (#9)


Hello, niels.

I set up your project and opened it on my Firefox 77.0.1.
I got an error "Firefox can not connect to https://localhost/webrtc-php/serverGet.php?unique=899215"

[image]<https://user-images.githubusercontent.com/12077057/85197793-fee00200-b315-11ea-9244-21fb030da507.png>

and I also tried it on my chrome Version 83.0.4103.106, I got an error "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

[image]<https://user-images.githubusercontent.com/12077057/85197901-bb39c800-b316-11ea-999b-e26d691977bc.png>

could you please tell me how to solve these errors?

**Comment by xuzhousoft09** [comment]
Thank you for your advice!
I will try to improve my ssl first!

**Comment by xuzhousoft09** [comment]
Hello, niels.

![image](https://user-images.githubusercontent.com/12077057/85305059-19b1a280-b4df-11ea-8ea1-e156a8da5089.png)

Based on https://laraweb.net/environment/3722/
I set up a localhost openssl serve on my wampserver 2.5.

But I got the same error again.
May I use the localhost server with https to set up this project?

**Comment by nielsbaloe** [comment]
Hi,

I can not imagine a localhost having a valid SSL certificate, because as far as I have knowledge about SSL, it is always connected to a domainname. So if that is true, you can not use it localhost. If I am wrong, then it should be possible.

It depends on your warnings. If you have any warning at all inside your javascript console, then it does not work. There should really be zero warnings there, and I saw in your last screenshot several warnings. Please fix all warnings first.

Does that help?


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: xuzhousoft09 <notifications@github.com>
Verzonden: maandag 22 juni 2020 17:20
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Firefox can not connect to https://localhost/webrtc-php/serverGet.php?unique=899215 (#9)


Hello, niels.

[Uploading image.png…]

Based on https://laraweb.net/environment/3722/
I set up a localhost openssl serve on my wampserver 2.5.

But I got the same error again.
May I use the localhost server with https to set up this project?

**Comment by xuzhousoft09** [comment]
Thank you for your advice!

**Comment by xuzhousoft09** [comment]
solved this error with:
npm install eventsource-polyfill

https://cnpmjs.org/package/eventsource-polyfill

**Comment by xuzhousoft09** [comment]
solved it by using older version
318775d14f96be0b658bc455918850c5e6ca4122

![image](https://user-images.githubusercontent.com/12077057/85394700-87160f80-b581-11ea-9e6f-a98b3ec862a5.png)

**Comment by nielsbaloe** [comment]
Hi,

Hmm ow really was the eventsource the problem? I had that library here a while ago, but I removed it because all browsers have eventsource (at first Edge didn't but now it does).

Which browser are you using? A very old one I guess? 😉

Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: xuzhousoft09 <notifications@github.com>
Verzonden: dinsdag 23 juni 2020 12:28
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] error "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection." (#9)


solved this error with:
npm install eventsource-polyfill

https://cnpmjs.org/package/eventsource-polyfill

**Comment by xuzhousoft09** [comment]
Hello, Niels

I am using Version 83.0.4103.106 (Official Build) (32-bit).

After changed to the old version, I still couldn't create the files on my windows10 PC.
I think my current situation is as same as [#1](https://github.com/nielsbaloe/webrtc-php/issues/1#issuecomment-621094547) 

> When I connect to the same url on different computers I also see the computers camera, but not both` of them at the same time. The browser console does not show any error messages. It prints  only "sending ws.send: client-call" on both computers.

I could get 'index.php?eventSource=yes' continuously.

![image](https://user-images.githubusercontent.com/12077057/85396415-4966b600-b584-11ea-8b7d-32664ed8a51b.png)

**Comment by nielsbaloe** [comment]
Hi,

Which browser? Chrome?
Can you copy-paste your full javascript console?


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: xuzhousoft09 <notifications@github.com>
Verzonden: dinsdag 23 juni 2020 13:01
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] error "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection." (#9)


Hello, Niels

I am using Version 83.0.4103.106 (Official Build) (32-bit).

After changed to the old version, I still couldn't create the files on my windows10 PC.
I think my current situation is as same as #1<https://github.com/nielsbaloe/webrtc-php/issues/1#issuecomment-621094547>

When I connect to the same url on different computers I also see the computers camera, but not > both` of them at the same time. The browser console does not show any error messages. It prints > only "sending ws.send: client-call" on both computers.

I could get 'index.php?eventSource=yes' continuously.

[image]<https://user-images.githubusercontent.com/12077057/85395801-48815480-b583-11ea-8d34-1e61376a85a3.png>

**Comment by Danny-Engelman** [comment]
**83.0.4103.106** is Chrome

![](https://i.imgur.com/dj8nyD1.jpg)

**Comment by nielsbaloe** [comment]
Well, chrome does not need a polyfill for eventSource. Eventsource has been supported in Chrome for many years.

Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Danny Engelman <notifications@github.com>
Verzonden: dinsdag 23 juni 2020 17:12
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] error "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection." (#9)


83.0.4103.106 is Chrome

[https://camo.githubusercontent.com/5221b67b40b38d1db7f70d12e44c5224fcfc465a/68747470733a2f2f692e696d6775722e636f6d2f646a386e7944312e6a7067]<https://camo.githubusercontent.com/5221b67b40b38d1db7f70d12e44c5224fcfc465a/68747470733a2f2f692e696d6775722e636f6d2f646a386e7944312e6a7067>
